[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "basic-sample",
    "engine", "maze",
]

[[bin]]
name = "basic-sample"
path = "basic-sample"

[[bin]]
name = "maze"
path = "maze"
