[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "basic_sample",
    "engine", "maze",
]

[[bin]]
name = "basic_sample"
path = "basic_sample"

[[bin]]
name = "maze"
path = "maze"
